// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MYDATA_LAB700105_H_
#define FLATBUFFERS_GENERATED_MYDATA_LAB700105_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Lab700105 {

struct Vec3;

struct RGBA;

struct Node;
struct NodeBuilder;

struct NodeList;
struct NodeListBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) RGBA FLATBUFFERS_FINAL_CLASS {
 private:
  float r_;
  float g_;
  float b_;
  float a_;

 public:
  RGBA()
      : r_(0),
        g_(0),
        b_(0),
        a_(0) {
  }
  RGBA(float _r, float _g, float _b, float _a)
      : r_(::flatbuffers::EndianScalar(_r)),
        g_(::flatbuffers::EndianScalar(_g)),
        b_(::flatbuffers::EndianScalar(_b)),
        a_(::flatbuffers::EndianScalar(_a)) {
  }
  float r() const {
    return ::flatbuffers::EndianScalar(r_);
  }
  float g() const {
    return ::flatbuffers::EndianScalar(g_);
  }
  float b() const {
    return ::flatbuffers::EndianScalar(b_);
  }
  float a() const {
    return ::flatbuffers::EndianScalar(a_);
  }
};
FLATBUFFERS_STRUCT_END(RGBA, 16);

struct Node FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_POSITION = 6,
    VT_COLOUR = 8
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  const Lab700105::Vec3 *position() const {
    return GetStruct<const Lab700105::Vec3 *>(VT_POSITION);
  }
  const Lab700105::RGBA *colour() const {
    return GetStruct<const Lab700105::RGBA *>(VT_COLOUR);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyField<Lab700105::Vec3>(verifier, VT_POSITION, 4) &&
           VerifyField<Lab700105::RGBA>(verifier, VT_COLOUR, 4) &&
           verifier.EndTable();
  }
};

struct NodeBuilder {
  typedef Node Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Node::VT_ID, id, 0);
  }
  void add_position(const Lab700105::Vec3 *position) {
    fbb_.AddStruct(Node::VT_POSITION, position);
  }
  void add_colour(const Lab700105::RGBA *colour) {
    fbb_.AddStruct(Node::VT_COLOUR, colour);
  }
  explicit NodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Node> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Node>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Node> CreateNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const Lab700105::Vec3 *position = nullptr,
    const Lab700105::RGBA *colour = nullptr) {
  NodeBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_colour(colour);
  builder_.add_position(position);
  return builder_.Finish();
}

struct NodeList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NodeListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NODES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Lab700105::Node>> *nodes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Lab700105::Node>> *>(VT_NODES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NODES) &&
           verifier.VerifyVector(nodes()) &&
           verifier.VerifyVectorOfTables(nodes()) &&
           verifier.EndTable();
  }
};

struct NodeListBuilder {
  typedef NodeList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_nodes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Lab700105::Node>>> nodes) {
    fbb_.AddOffset(NodeList::VT_NODES, nodes);
  }
  explicit NodeListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NodeList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NodeList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NodeList> CreateNodeList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Lab700105::Node>>> nodes = 0) {
  NodeListBuilder builder_(_fbb);
  builder_.add_nodes(nodes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<NodeList> CreateNodeListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Lab700105::Node>> *nodes = nullptr) {
  auto nodes__ = nodes ? _fbb.CreateVector<::flatbuffers::Offset<Lab700105::Node>>(*nodes) : 0;
  return Lab700105::CreateNodeList(
      _fbb,
      nodes__);
}

inline const Lab700105::Node *GetNode(const void *buf) {
  return ::flatbuffers::GetRoot<Lab700105::Node>(buf);
}

inline const Lab700105::Node *GetSizePrefixedNode(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Lab700105::Node>(buf);
}

template <bool B = false>
inline bool VerifyNodeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Lab700105::Node>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedNodeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Lab700105::Node>(nullptr);
}

inline void FinishNodeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Lab700105::Node> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedNodeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Lab700105::Node> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Lab700105

#endif  // FLATBUFFERS_GENERATED_MYDATA_LAB700105_H_
